name: Get openings-1b information

on:
  schedule:
    - cron: '20 12 * * 2' # 20:20 Tue UTC+8
    - cron: '20 1 * * 6' # 9:20 Sat UTC+8

jobs:
  job-get-openings-1b-info:
    uses: ./.github/workflows/get-information.yml
    secrets: inherit
    with:
      file-name: openings-1b
