name: Get openings-cr information

on:
  schedule:
    # - cron: '50 12 * * 2' # 20:50 Tue UTC+8
    - cron: '50 1 * * 6' # 9:50 Sat UTC+8

jobs:
  job-get-openings-cr-info:
    uses: ./.github/workflows/get-information.yml
    secrets: inherit
    with:
      file-name: openings-cr
  job-keep-openings-cr-alive:
    uses: ./.github/workflows/auto-enable-workflow.yml
