name: Get travel-taipei information

on:
  schedule:
    - cron: '55 4 * * 5' # 12:55 Fri UTC+8

jobs:
  job-get-travel-taipei-info:
    uses: ./.github/workflows/get-information.yml
    secrets: inherit
    with:
      file-name: travel-taipei
