name: Get weather information

on:
  schedule:
    - cron: '0 14 * * *' # 22:00 UTC+8

jobs:
  job-get-weather-info:
    uses: ./.github/workflows/get-information.yml
    secrets: inherit
    with:
      file-name: weather
